dependencies:
  - name: kube-toy
    version: ~0.1.0-any
    repository: cm://h.cfcr.io/teacherspayteachers/default
  - name: kube-service
    version: ~0.1.1-any
    repository: cm://h.cfcr.io/teacherspayteachers/default
